dist: xenial
sudo: required
language: generic
env:
    - TRAVIS_PYTHON_VERSION="3.7"
    - TRAVIS_PYTHON_VERSION="3.8"
    
before_install:
    - python -m pip install --upgrade pip
    
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-env python="${TRAVIS_PYTHON_VERSION}" pytest pytest-cov pyyaml
    - source activate test-env
    - pip install --user -r requirements.txt
    - pip install configparser
    - pip install coveralls
    
script:
    #- pytest -v --cov=watex --cov-report=tests --ignore=watex/utils | python -m pytest --cov-fail-under=20
    - pytest -v --cov=tests/
    
after_failure:
    - cat config.log